#!/usr/bin/env python3
"""Convenience runner that isolates each run's allure results under a timestamp.

Why this exists:
  ``pytest.ini`` historically set ``--alluredir=reports/allure-results`` (and
  ``--clean-alluredir``), so every run wrote to the SAME directory and the HTML
  report at ``reports/allure-report`` was overwritten on each run. To keep
  per-run results, this wrapper computes a timestamped run dir and passes it
  dynamically as ``--alluredir`` (and the report output dir), so each run lands
  in its own folder: ``reports/<YYYYMMDD-HHMMSS>/allure-results`` and
  ``reports/<YYYYMMDD-HHMMSS>/allure-report``.

Usage:
  python run.py            # run all tests (passes any extra args to pytest)
  python run.py -k tpm     # run only tests matching "tpm"
  python run.py --help     # show pytest help (args forwarded)

Environment variables honored:
  ALAYA_RUN_DIR   overrides the timestamped dir name (e.g. "my-run-42"); when
                   set, NO timestamp is appended (useful for re-running into a
                   fixed dir or for CI naming).
  ALAYA_SKIP_ALLURE_GEN=1  skip the allure HTML generation (passed through to
                   conftest; documented here for discoverability).
"""

import os
import subprocess
import sys
from datetime import datetime


def _resolve_run_dir():
    """Return the run directory name (no path). Honors ALAYA_RUN_DIR override."""
    override = os.environ.get("ALAYA_RUN_DIR", "").strip()
    if override:
        return override
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def main():
    run_dir = _resolve_run_dir()
    results_dir = os.path.join("reports", run_dir, "allure-results")
    report_dir = os.path.join("reports", run_dir, "allure-report")
    os.makedirs(results_dir, exist_ok=True)

    # Forward ALAYA_RUN_DIR to the pytest subprocess so conftest.py resolves the
    # SAME run dir for the HTML generation step (results/report stay in sync).
    env = dict(os.environ)
    env["ALAYA_RUN_DIR"] = run_dir

    # Build the pytest command: keep pytest.ini addopts EXCEPT --alluredir /
    # --clean-alluredir (those are removed from pytest.ini; we inject our own
    # dynamic --alluredir here). Extra CLI args from the user are appended last
    # so they can override anything pytest.ini sets.
    pytest_args = [
        sys.executable,
        "-m",
        "pytest",
        f"--alluredir={results_dir}",
        "--clean-alluredir",
    ]
    # Pass through any user args (e.g. -k, -m, --collect-only, file paths).
    pytest_args += sys.argv[1:]

    print(f"[run] run_dir={run_dir}")
    print(f"[run] allure-results -> {results_dir}")
    print(f"[run] allure-report  -> {report_dir} (generated after session)")
    print(f"[run] cmd: {' '.join(pytest_args)}")

    proc = subprocess.run(pytest_args, env=env)
    # The allure HTML report is generated by conftest's session fixture
    # (generate_allure_report), which runs INSIDE the pytest process and uses
    # the same ALAYA_RUN_DIR. So nothing more to do here — just propagate the
    # exit code so CI/Make can detect failure.
    return proc.returncode


if __name__ == "__main__":
    sys.exit(main())
